apiVersion: v1
kind: Pod
metadata:
  name: sgx-sample-demo
  namespace: default
spec:
  containers:
    - image: ljoshuay/sgx_sample_code:v1.2_ubuntu
      imagePullPolicy: IfNotPresent
      name: sgx-sample-code
      workingDir: "/opt/intel/sgxsdk/SampleCode/"
      command: ["/opt/intel/sgxsdk/SampleCode/SampleRun.sh"]
      resources:
        ## resources of the pod
        requests:
          sgx.intel.com/enclave: "1"
          sgx.intel.com/epc: "1024Ki"
          sgx.intel.com/provision: "1"
        limits:
          sgx.intel.com/enclave: "1"
          sgx.intel.com/epc: "1024Ki"
          sgx.intel.com/provision: "1"
      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        capabilities:
          add: ["IPC_LOCK"]
      volumeMounts:
        - name: ephemeral
          mountPath: /tmp/SGXSampleCode
  volumes:
    - name: ephemeral
      emptyDir: {}
